"""Core doc-update orchestration, extracted from the CLI for testability.

The CLI (cli.py) is responsible only for config loading, output rendering,
and error handling.  All business logic lives here.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ai_reviewer.config import AnthropicApiConfig, DocGenerationSettings
    from ai_reviewer.docs.analyzer import DocDraft, DocSuggestion
    from ai_reviewer.github.client import GitHubClient

logger = logging.getLogger(__name__)


@dataclass
class DocUpdateResult:
    """Outcome of a doc-update run."""

    successful: list[DocDraft] = field(default_factory=list)
    failed: list[DocDraft] = field(default_factory=list)
    pr_url: str | None = None
    skipped: bool = False
    skip_reason: str | None = None


def _build_pr_body(pr_number: int, pr_html_url: str, successful: list[DocDraft]) -> str:
    files_list = "\n".join(f"- `{d.suggestion.file}`" for d in successful)
    changes = "\n".join(f"**{d.suggestion.file}**: {d.suggestion.reason}" for d in successful)
    return (
        f"## Automatic Documentation Update\n\n"
        f"This PR was opened automatically by the AI Code Reviewer after "
        f"[PR #{pr_number}]({pr_html_url}) was merged.\n\n"
        f"### Updated files\n\n{files_list}\n\n"
        f"### What changed\n\n{changes}"
        f"\n\n---\n*Generated by `ai-reviewer update-docs`. "
        "Review the changes and merge if correct — nothing was auto-merged.*"
    )


async def run_doc_update(
    *,
    repo: str,
    pr_number: int,
    gh: GitHubClient,
    anthropic_cfg: AnthropicApiConfig,
    doc_generation: DocGenerationSettings,
    base: str | None = None,
    dry_run: bool = False,
) -> DocUpdateResult:
    """Detect stale docs, generate AI updates, and optionally open a PR.

    Returns a :class:`DocUpdateResult`.  When *dry_run* is ``True`` the PR
    creation step is skipped — ``result.pr_url`` will be ``None`` and
    ``result.successful`` contains the generated drafts for the caller to
    display.
    """
    from ai_reviewer.docs.analyzer import DocAnalyzer, DocSuggestion, generate_doc_drafts

    if not doc_generation.enabled:
        return DocUpdateResult(skipped=True, skip_reason="doc_generation not enabled")

    pr = gh.get_pull_request(repo, pr_number)
    base_branch = base or pr.base.ref

    if not dry_run and gh.has_open_doc_update_pr(repo, base_branch):
        return DocUpdateResult(
            skipped=True,
            skip_reason=f"open doc-update PR already exists for {base_branch}",
        )

    ref = pr.merge_commit_sha or pr.head.sha
    repo_config = gh.load_repo_config(repo, ref)
    doc_config = repo_config.get("documentation") if repo_config else None

    # Apply per-repo doc_generation overrides on top of the server's defaults.
    repo_docgen: dict = repo_config.get("doc_generation", {}) if repo_config else {}
    if repo_docgen.get("enabled") is False:
        return DocUpdateResult(skipped=True, skip_reason="doc_generation disabled in repo config")
    effective_model: str = repo_docgen.get("model") or doc_generation.model
    effective_max_files: int = int(repo_docgen.get("max_files") or doc_generation.max_files)
    effective_pr_labels: list[str] = repo_docgen.get("pr_labels") or doc_generation.pr_labels
    effective_pr_draft: bool = repo_docgen.get("pr_draft", doc_generation.pr_draft)

    pr_files = list(pr.get_files())
    changed_paths = [f.filename for f in pr_files]
    changed_paths_with_status = {f.filename: getattr(f, "status", "modified") for f in pr_files}

    # Mapping-based suggestions (source_to_docs_mapping)
    mapping_suggestions: list[DocSuggestion] = []
    if doc_config and doc_config.get("source_to_docs_mapping"):
        analyzer = DocAnalyzer(
            changed_paths=changed_paths,
            changed_paths_with_status=changed_paths_with_status,
            existing_repo_paths=set(),
            doc_config=doc_config,
        )
        mapping_suggestions = analyzer.check_source_to_docs_mapping()

    # HTML scan suggestions — repo config takes precedence over server defaults.
    html_suggestions: list[DocSuggestion] = []
    effective_static_dirs: list[str] = (
        repo_docgen.get("static_docs_dirs")
        or (doc_config.get("static_docs_dirs") if doc_config else None)
        or doc_generation.static_docs_dirs
    )
    if effective_static_dirs:
        already_covered = {s.file for s in mapping_suggestions}
        html_paths = gh.get_html_files_in_dirs(repo, ref, effective_static_dirs)
        for html_path in html_paths:
            if html_path not in already_covered:
                html_suggestions.append(
                    DocSuggestion(
                        file=html_path,
                        reason=(
                            f"Static HTML page in `{html_path}` — scanning for updates "
                            "triggered by code changes in this PR."
                        ),
                    )
                )

    all_suggestions = mapping_suggestions + html_suggestions
    if not all_suggestions:
        return DocUpdateResult(skipped=True, skip_reason="no stale documentation detected")

    diff = gh.get_pr_diff(pr)
    drafts = await generate_doc_drafts(
        suggestions=all_suggestions,
        diff=diff,
        repo_name=repo,
        ref=ref,
        anthropic_cfg=anthropic_cfg,
        gh=gh,
        model=effective_model,
        max_files=effective_max_files,
    )

    successful = [d for d in drafts if d.updated_content and not d.error]
    failed = [d for d in drafts if d.error]

    if not successful:
        return DocUpdateResult(
            failed=failed,
            skipped=True,
            skip_reason="no doc updates needed after scanning all candidates",
        )

    if dry_run:
        return DocUpdateResult(successful=successful, failed=failed)

    pr_url = gh.create_doc_update_pr(
        repo_name=repo,
        base_branch=base_branch,
        base_sha=ref,
        updates=successful,
        pr_title=f"docs: auto-update for PR #{pr_number} — {pr.title}",
        pr_body=_build_pr_body(pr_number, pr.html_url, successful),
        assignee=pr.user.login if pr.user else None,
        labels=effective_pr_labels,
        draft=effective_pr_draft,
    )
    return DocUpdateResult(successful=successful, failed=failed, pr_url=pr_url)
