# Cloud Build configuration for AI Code Reviewer
# Automatically builds and deploys to Cloud Run on push
#
# Setup:
#   1. Enable Cloud Build API: gcloud services enable cloudbuild.googleapis.com
#   2. Enable Cloud Run API: gcloud services enable run.googleapis.com
#   3. Grant Cloud Build permission to deploy to Cloud Run:
#      gcloud projects add-iam-policy-binding $PROJECT_ID \
#        --member="serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
#        --role="roles/run.admin"
#   4. Connect your repo in Cloud Build triggers
#
# Secrets should be stored in Secret Manager:
#   gcloud secrets create CURSOR_API_KEY --data-file=-
#   gcloud secrets create GITHUB_TOKEN --data-file=-
#   gcloud secrets create GITHUB_WEBHOOK_SECRET --data-file=-

substitutions:
  _SERVICE_NAME: ai-code-reviewer
  _REGION: europe-west3
  # Override these in trigger or command line:
  # _MIN_INSTANCES: '0'  # Set to 1 for no cold starts (costs more)

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Required for GitHub webhooks
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300s'  # 5 min for long reviews
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'  # Scale to zero when idle
      - '--max-instances'
      - '5'
      # Secrets from Secret Manager (GitHub App auth)
      - '--set-secrets'
      - 'CURSOR_API_KEY=CURSOR_API_KEY:latest,GITHUB_APP_ID=GITHUB_APP_ID:latest,GITHUB_APP_PRIVATE_KEY=GITHUB_APP_PRIVATE_KEY:latest,GITHUB_WEBHOOK_SECRET=GITHUB_WEBHOOK_SECRET:latest'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
