"""GitHub comment formatter for review output."""

from ai_reviewer.models.findings import Severity
from ai_reviewer.models.review import ConsolidatedReview


class GitHubFormatter:
    """Formats review output for GitHub comments."""

    SEVERITY_EMOJI = {
        Severity.CRITICAL: "🔴",
        Severity.WARNING: "🟡",
        Severity.SUGGESTION: "💡",
        Severity.NITPICK: "📝",
    }

    SEVERITY_LABEL = {
        Severity.CRITICAL: "Critical",
        Severity.WARNING: "Warning",
        Severity.SUGGESTION: "Suggestion",
        Severity.NITPICK: "Nitpick",
    }

    def format_review(self, review: ConsolidatedReview) -> str:
        """Format a consolidated review as a GitHub comment.

        Args:
            review: Consolidated review to format

        Returns:
            Markdown formatted comment
        """
        lines = [
            "## 🤖 AI Code Review",
            "",
            self._format_header(review),
            "",
            "---",
            "",
        ]

        if not review.findings:
            lines.extend(
                [
                    "### ✅ No Issues Found",
                    "",
                    "All agents reviewed the code and found no issues. LGTM! 🎉",
                    "",
                ]
            )
        else:
            # Group by severity
            by_severity = self._group_by_severity(review)

            for severity in [
                Severity.CRITICAL,
                Severity.WARNING,
                Severity.SUGGESTION,
                Severity.NITPICK,
            ]:
                findings = by_severity.get(severity, [])
                if findings:
                    lines.extend(
                        self._format_severity_section(severity, findings, review.agent_count)
                    )
                    lines.append("")

        lines.extend(
            [
                "---",
                "",
                self._format_footer(review),
            ]
        )

        return "\n".join(lines)

    def _format_header(self, review: ConsolidatedReview) -> str:
        """Format the review header."""
        consensus_pct = int(review.review_quality_score * 100)
        time_sec = review.total_review_time_ms / 1000

        return (
            f"**Reviewed by {review.agent_count} agents** | "
            f"Quality score: {consensus_pct}% | "
            f"Review time: {time_sec:.1f}s"
        )

    def _group_by_severity(self, review: ConsolidatedReview) -> dict:
        """Group findings by severity."""
        groups: dict = {}
        for finding in review.findings:
            if finding.severity not in groups:
                groups[finding.severity] = []
            groups[finding.severity].append(finding)
        return groups

    def _format_severity_section(
        self, severity: Severity, findings: list, agent_count: int
    ) -> list[str]:
        """Format a section for a severity level."""
        emoji = self.SEVERITY_EMOJI[severity]
        label = self.SEVERITY_LABEL[severity]

        lines = [
            f"### {emoji} {label} ({len(findings)})",
            "",
        ]

        for i, finding in enumerate(findings, 1):
            # Consensus indicator
            consensus_count = len(finding.agreeing_agents)
            consensus_str = f"{consensus_count}/{agent_count} agents"
            if consensus_count == agent_count:
                consensus_str += " ✓"

            lines.extend(
                [
                    f"#### {i}. {finding.title}",
                    f"**File:** `{finding.file_path}` (line {finding.line_start}"
                    + (f"-{finding.line_end}" if finding.line_end else "")
                    + f") | **Consensus:** {consensus_str}",
                    "",
                    finding.description,
                    "",
                ]
            )

            if finding.suggested_fix:
                lines.extend(
                    [
                        "**Suggested fix:**",
                        "```",
                        finding.suggested_fix,
                        "```",
                        "",
                    ]
                )

            # Show which agents found this (for transparency)
            agents_str = ", ".join(finding.agreeing_agents[:3])
            if len(finding.agreeing_agents) > 3:
                agents_str += f" (+{len(finding.agreeing_agents) - 3} more)"
            lines.append(f"> *Found by: {agents_str}*")
            lines.append("")

        return lines

    def _format_footer(self, review: ConsolidatedReview) -> str:
        """Format the review footer."""
        return (
            "<sub>🤖 Generated by "
            "[AI Code Reviewer](https://github.com/calimero-network/ai-code-reviewer) | "
            f"Review ID: `{review.id}`</sub>"
        )

    def get_review_action(self, review: ConsolidatedReview, allow_approve: bool = True) -> str:
        """Determine the GitHub review action based on findings.

        Args:
            review: Consolidated review
            allow_approve: Whether to allow APPROVE action (False in GitHub Actions)

        Returns:
            GitHub review action: "APPROVE", "REQUEST_CHANGES", or "COMMENT"
        """
        if review.has_critical_issues:
            return "REQUEST_CHANGES"
        elif not review.findings and allow_approve:
            return "APPROVE"
        else:
            return "COMMENT"


def format_review_as_json(review: ConsolidatedReview) -> dict:
    """Format review as JSON-serializable dict."""
    return {
        "review_id": review.id,
        "created_at": review.created_at.isoformat(),
        "repo": review.repo,
        "pr_number": review.pr_number,
        "summary": review.summary,
        "quality_score": review.review_quality_score,
        "agent_count": review.agent_count,
        "total_time_ms": review.total_review_time_ms,
        "findings": [
            {
                "id": f.id,
                "file_path": f.file_path,
                "line_start": f.line_start,
                "line_end": f.line_end,
                "severity": f.severity.value,
                "category": f.category.value,
                "title": f.title,
                "description": f.description,
                "suggested_fix": f.suggested_fix,
                "consensus_score": f.consensus_score,
                "agreeing_agents": f.agreeing_agents,
                "confidence": f.confidence,
            }
            for f in review.findings
        ],
        "findings_by_severity": {
            k.value: v for k, v in review.findings_by_severity.items() if v > 0
        },
    }
